<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Tink</RootNamespace>
    <AssemblyName>Tink</AssemblyName>
    <Version>0.1.0</Version>
    <Description>tink data-flow node frame protocol (universal, language-agnostic)</Description>
  </PropertyGroup>

</Project>